### ISSUE TITLE
Rare MultiThreaded crash when using synchronous requests in multiple threads

### ISSUE THREAD

**Issue by LeeMatthewHiggins** [pokeb/asi-http-request#155]
Seems to be a Multi threading issue when running multiple startSynchronous requests in operations. (I know we should use the ASIHTTP queue really)

crash backtrace.....
#0 0x01a0836b in CFHash ()
#1 0x01b04843 in ___CFBasicHashFindBucket_Linear ()
#2 0x01a0fc12 in CFBasicHashFindBucket ()
#3 0x01a0faec in CFDictionaryGetValue ()
#4 0x01a9dbcc in _CFStreamUnscheduleFromRunLoop ()
#5 0x01a9db89 in _CFStreamUnscheduleFromRunLoop ()
#6 0x001b7bf8 in -[ASIHTTPRequest unscheduleReadStream](self=0xb84f200, _cmd=0x20809d) at ASIHTTPRequest.m:3455
#7 0x001b764e in -[ASIHTTPRequest destroyReadStream](self=0xb84f200, _cmd=0x2080c5) at ASIHTTPRequest.m:3409
#8 0x001b647b in -[ASIHTTPRequest handleStreamComplete](self=0xb84f200, _cmd=0x208121) at ASIHTTPRequest.m:3231
#9 0x001b38fa in -[ASIHTTPRequest handleNetworkEvent:](self=0xb84f200, _cmd=0x20814b, type=16) at ASIHTTPRequest.m:2933
#10 0x0019f861 in ReadStreamClientCallBack (readStream=0xf673420, type=16, clientCallBackInfo=0xb84f200) at ASIHTTPRequest.m:52
#11 0x01a9c953 in _signalEventSync ()
#12 0x01a9c8be in _cfstream_shared_signalEventSync ()
#13 0x01ace8ff in **CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE0_PERFORM_FUNCTION** ()
#14 0x01a2c88b in __CFRunLoopDoSources0 ()
#15 0x01a2bd86 in __CFRunLoopRun ()
#16 0x01a2b840 in CFRunLoopRunSpecific ()
#17 0x01a2b761 in CFRunLoopRunInMode ()
#18 0x00415115 in -[NSRunLoop(NSRunLoop) runMode:beforeDate:]()
#19 0x001a3725 in -[ASIHTTPRequest startSynchronous](self=0xb84f200, _cmd=0x20450c) at ASIHTTPRequest.m:758

**Comment by LeeMatthewHiggins** [comment]
This is the same bug as 104. See 104 for possible fix... Sorry for dup.
